
openai_key: ""
email_sender: "karan.bhavnani0110@gmail.com"
email_password: ""
email_receiver: "notify@rupanibusiness.com"
smtp_server: "smtp.gmail.com"
smtp_port: 587
tally_host: "localhost"
tally_port: 9000